// JScript для записи VBA-модулей в кодировке Windows-1251
// Запуск: cscript //nologo write_modules.js

var fso = new ActiveXObject("Scripting.FileSystemObject");
var shell = new ActiveXObject("WScript.Shell");
var basePath = "L:\\PROject\\SysW\\";

function writeFile1251(filename, content) {
    var path = basePath + filename;
    // Создаём ADODB.Stream для записи в Windows-1251
    var stream = new ActiveXObject("ADODB.Stream");
    stream.Type = 2; // adTypeText
    stream.Charset = "windows-1251";
    stream.Open();
    stream.WriteText(content, 0); // 0 = не добавлять BOM
    stream.SaveToFile(path, 2); // 2 = adSaveCreateOverWrite
    stream.Close();
    WScript.Echo("OK: " + filename);
}

// ============================================================
// 1. Mod_Utils.bas
// ============================================================
var content = '';
content += 'Attribute VB_Name = "Mod_Utils"\r\n';
content += 'Option Explicit\r\n';
content += '\r\n';
content += "' ============================================================\r\n";
content += "' Модуль: Mod_Utils\r\n";
content += "' Назначение: вспомогательные функции для работы с Excel и SQLite\r\n";
content += "' ============================================================\r\n";
content += '\r\n';
content += "' Константы для SQLite\r\n";
content += 'Public Const SQLITE_DLL As String = "C:\\SQLite\\sqlite3.dll"\r\n';
content += 'Public Const DB_PATH As String = "C:\\SQLite\\SysW.db"\r\n';
content += '\r\n';
content += "' Тип для хранения данных заказ-наряда\r\n";
content += 'Public Type OrderHeader\r\n';
content += '    OrderNumber As String\r\n';
content += '    ClientName As String\r\n';
content += '    CarModel As String\r\n';
content += '    CarPlate As String\r\n';
content += '    Mileage As Long\r\n';
content += '    DateIn As Date\r\n';
content += '    DateOut As Date\r\n';
content += '    Status As String\r\n';
content += 'End Type\r\n';
content += '\r\n';
content += "' Функция: проверка существования файла\r\n";
content += 'Public Function FileExists(ByVal FilePath As String) As Boolean\r\n';
content += '    On Error Resume Next\r\n';
content += '    FileExists = (Len(Dir(FilePath)) > 0)\r\n';
content += '    On Error GoTo 0\r\n';
content += 'End Function\r\n';
content += '\r\n';
content += "' Функция: получение имени текущего пользователя Windows\r\n";
content += 'Public Function GetCurrentUser() As String\r\n';
content += '    GetCurrentUser = Environ("USERNAME")\r\n';
content += 'End Function\r\n';
content += '\r\n';
content += "' Функция: форматирование даты в строку SQLite (ГГГГ-ММ-ДД)\r\n";
content += 'Public Function FormatDateSQL(ByVal d As Date) As String\r\n';
content += '    FormatDateSQL = Format(d, "yyyy-mm-dd")\r\n';
content += 'End Function\r\n';
content += '\r\n';
content += "' Процедура: запись в лог-файл\r\n";
content += 'Public Sub WriteLog(ByVal Message As String)\r\n';
content += '    Dim LogPath As String\r\n';
content += '    Dim F As Long\r\n';
content += '    LogPath = ThisWorkbook.Path & "\\log.txt"\r\n';
content += '    F = FreeFile\r\n';
content += '    Open LogPath For Append As #F\r\n';
content += '    Print #F, Now & " - " & Message\r\n';
content += '    Close #F\r\n';
content += 'End Sub\r\n';
writeFile1251("Mod_Utils.bas", content);

// ============================================================
// 2. Mod_OrderHeader.bas
// ============================================================
content = '';
content += 'Attribute VB_Name = "Mod_OrderHeader"\r\n';
content += 'Option Explicit\r\n';
content += '\r\n';
content += "' ============================================================\r\n";
content += "' Модуль: Mod_OrderHeader\r\n";
content += "' Назначение: автоматическое заполнение шапки заказ-наряда\r\n";
content += "' ============================================================\r\n";
content += '\r\n';
content += "' Константы для столбцов\r\n";
content += 'Private Const COL_ORDER_NUM As String = "B"\r\n';
content += 'Private Const COL_CLIENT As String = "C"\r\n';
content += 'Private Const COL_CAR_MODEL As String = "D"\r\n';
content += 'Private Const COL_CAR_PLATE As String = "E"\r\n';
content += 'Private Const COL_MILEAGE As String = "F"\r\n';
content += 'Private Const COL_DATE_IN As String = "G"\r\n';
content += 'Private Const COL_DATE_OUT As String = "H"\r\n';
content += 'Private Const COL_STATUS As String = "I"\r\n';
content += '\r\n';
content += "' Обработчик изменения ячейки (вызывается из листа)\r\n";
content += 'Public Sub OnWorksheetChange(ByVal Target As Range)\r\n';
content += '    If Target.Cells.Count > 1 Then Exit Sub\r\n';
content += '    If Intersect(Target, Range(COL_ORDER_NUM & ":" & COL_ORDER_NUM)) Is Nothing Then Exit Sub\r\n';
content += '    If Target.Row < 2 Then Exit Sub\r\n';
content += '    Dim OrderNum As String\r\n';
content += '    OrderNum = Trim(Target.Value)\r\n';
content += '    If OrderNum = "" Then Exit Sub\r\n';
content += '\r\n';
content += '    '' Поиск заказа в SQLite\r\n';
content += '    Dim Header As OrderHeader\r\n';
content += '    If FindOrder(OrderNum, Header) Then\r\n';
content += '        '' Заполняем шапку\r\n';
content += '        Application.EnableEvents = False\r\n';
content += '        Range(COL_CLIENT & Target.Row).Value = Header.ClientName\r\n';
content += '        Range(COL_CAR_MODEL & Target.Row).Value = Header.CarModel\r\n';
content += '        Range(COL_CAR_PLATE & Target.Row).Value = Header.CarPlate\r\n';
content += '        Range(COL_MILEAGE & Target.Row).Value = Header.Mileage\r\n';
content += '        Range(COL_DATE_IN & Target.Row).Value = Header.DateIn\r\n';
content += '        Range(COL_DATE_OUT & Target.Row).Value = Header.DateOut\r\n';
content += '        Range(COL_STATUS & Target.Row).Value = Header.Status\r\n';
content += '        Application.EnableEvents = True\r\n';
content += '    End If\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Функция: поиск заказа в SQLite по номеру\r\n";
content += 'Private Function FindOrder(ByVal OrderNum As String, ByRef Header As OrderHeader) As Boolean\r\n';
content += '    '' Заглушка — в реальности здесь будет SQL-запрос к SQLite\r\n';
content += '    '' Пока возвращаем тестовые данные\r\n';
content += '    If OrderNum = "ЗН-001" Then\r\n';
content += '        Header.OrderNumber = OrderNum\r\n';
content += '        Header.ClientName = "Иванов И.И."\r\n';
content += '        Header.CarModel = "Toyota Camry"\r\n';
content += '        Header.CarPlate = "А123ВС77"\r\n';
content += '        Header.Mileage = 45000\r\n';
content += '        Header.DateIn = DateSerial(2026, 7, 1)\r\n';
content += '        Header.DateOut = DateSerial(2026, 7, 5)\r\n';
content += '        Header.Status = "В работе"\r\n';
content += '        FindOrder = True\r\n';
content += '    Else\r\n';
content += '        FindOrder = False\r\n';
content += '    End If\r\n';
content += 'End Function\r\n';
writeFile1251("Mod_OrderHeader.bas", content);

// ============================================================
// 3. Mod_Import.bas
// ============================================================
content = '';
content += 'Attribute VB_Name = "Mod_Import"\r\n';
content += 'Option Explicit\r\n';
content += '\r\n';
content += "' ============================================================\r\n";
content += "' Модуль: Mod_Import\r\n";
content += "' Назначение: импорт данных из Excel в SQLite\r\n";
content += "' ============================================================\r\n";
content += '\r\n';
content += "' Константы\r\n";
content += 'Private Const START_ROW As Long = 2\r\n';
content += 'Private Const COL_ORDER As Long = 2  '' B\r\n';
content += 'Private Const COL_CLIENT As Long = 3 '' C\r\n';
content += 'Private Const COL_CAR As Long = 4    '' D\r\n';
content += 'Private Const COL_PLATE As Long = 5  '' E\r\n';
content += 'Private Const COL_MILEAGE As Long = 6 '' F\r\n';
content += 'Private Const COL_DATE_IN As Long = 7 '' G\r\n';
content += 'Private Const COL_DATE_OUT As Long = 8 '' H\r\n';
content += 'Private Const COL_STATUS As Long = 9  '' I\r\n';
content += '\r\n';
content += "' Главная процедура импорта\r\n";
content += 'Public Sub RunImport()\r\n';
content += '    Dim ws As Worksheet\r\n';
content += '    Dim LastRow As Long\r\n';
content += '    Dim i As Long\r\n';
content += '    Dim ImportCount As Long\r\n';
content += '    Set ws = ThisWorkbook.Sheets("Лист1")\r\n';
content += '    LastRow = ws.Cells(ws.Rows.Count, COL_ORDER).End(xlUp).Row\r\n';
content += '    If LastRow < START_ROW Then\r\n';
content += '        MsgBox "Нет данных для импорта.", vbInformation, "Импорт"\r\n';
content += '        Exit Sub\r\n';
content += '    End If\r\n';
content += '    ImportCount = 0\r\n';
content += '    For i = START_ROW To LastRow\r\n';
content += '        If Trim(ws.Cells(i, COL_ORDER).Value) <> "" Then\r\n';
content += '            '' Здесь будет вызов SQLite-вставки\r\n';
content += '            ImportCount = ImportCount + 1\r\n';
content += '        End If\r\n';
content += '    Next i\r\n';
content += '    MsgBox "Импорт завершён. Обработано строк: " & ImportCount, vbInformation, "Импорт"\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Процедура: проверка данных перед импортом\r\n";
content += 'Public Function ValidateData(ByVal ws As Worksheet) As String\r\n';
content += '    Dim LastRow As Long\r\n';
content += '    Dim i As Long\r\n';
content += '    Dim Errors As String\r\n';
content += '    LastRow = ws.Cells(ws.Rows.Count, COL_ORDER).End(xlUp).Row\r\n';
content += '    For i = START_ROW To LastRow\r\n';
content += '        If Trim(ws.Cells(i, COL_ORDER).Value) <> "" Then\r\n';
content += '            If Trim(ws.Cells(i, COL_CLIENT).Value) = "" Then\r\n';
content += '                Errors = Errors & "Строка " & i & ": не указан клиент" & vbCrLf\r\n';
content += '            End If\r\n';
content += '            If Trim(ws.Cells(i, COL_CAR).Value) = "" Then\r\n';
content += '                Errors = Errors & "Строка " & i & ": не указан автомобиль" & vbCrLf\r\n';
content += '            End If\r\n';
content += '        End If\r\n';
content += '    Next i\r\n';
content += '    ValidateData = Errors\r\n';
content += 'End Function\r\n';
writeFile1251("Mod_Import.bas", content);

// ============================================================
// 4. Mod_ButtonDispatcher.bas
// ============================================================
content = '';
content += 'Attribute VB_Name = "Mod_ButtonDispatcher"\r\n';
content += 'Option Explicit\r\n';
content += '\r\n';
content += "' ============================================================\r\n";
content += "' Модуль: Mod_ButtonDispatcher\r\n";
content += "' Назначение: диспетчер кнопок на листах\r\n";
content += "' ============================================================\r\n";
content += '\r\n';
content += "' Обработчик нажатия кнопки ""Импорт""\r\n";
content += 'Public Sub btnImport_Click()\r\n';
content += '    Mod_Import.RunImport\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Обработчик нажатия кнопки ""Тест""\r\n";
content += 'Public Sub btnTest_Click()\r\n';
content += '    Mod_MinimalTestRunner.RunAllTests\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Обработчик нажатия кнопки ""Очистить""\r\n";
content += 'Public Sub btnClear_Click()\r\n';
content += '    Dim ws As Worksheet\r\n';
content += '    Dim Response As VbMsgBoxResult\r\n';
content += '    Set ws = ActiveSheet\r\n';
content += '    Response = MsgBox("Очистить все данные на листе " & ws.Name & "?", vbYesNo + vbQuestion, "Очистка")\r\n';
content += '    If Response = vbYes Then\r\n';
content += '        ws.Cells.ClearContents\r\n';
content += '        MsgBox "Данные очищены.", vbInformation, "Очистка"\r\n';
content += '    End If\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Обработчик нажатия кнопки ""Обновить""\r\n";
content += 'Public Sub btnRefresh_Click()\r\n';
content += '    MsgBox "Обновление данных из SQLite...", vbInformation, "Обновление"\r\n';
content += '    '' Здесь будет вызов загрузки из SQLite\r\n';
content += 'End Sub\r\n';
writeFile1251("Mod_ButtonDispatcher.bas", content);

// ============================================================
// 5. Mod_MinimalTestRunner.bas
// ============================================================
content = '';
content += 'Attribute VB_Name = "Mod_MinimalTestRunner"\r\n';
content += 'Option Explicit\r\n';
content += '\r\n';
content += "' ============================================================\r\n";
content += "' Модуль: Mod_MinimalTestRunner\r\n";
content += "' Назначение: минимальный набор тестов для проверки модулей\r\n";
content += "' ============================================================\r\n";
content += '\r\n';
content += "' Главная процедура запуска тестов\r\n";
content += 'Public Sub RunAllTests()\r\n';
content += '    Dim TotalTests As Long\r\n';
content += '    Dim PassedTests As Long\r\n';
content += '    Dim FailedTests As Long\r\n';
content += '    TotalTests = 0\r\n';
content += '    PassedTests = 0\r\n';
content += '    FailedTests = 0\r\n';
content += '\r\n';
content += '    '' Тест 1: проверка FileExists\r\n';
content += '    TotalTests = TotalTests + 1\r\n';
content += '    If Test_FileExists() Then\r\n';
content += '        PassedTests = PassedTests + 1\r\n';
content += '        Debug.Print "  [OK] Тест FileExists пройден"\r\n';
content += '    Else\r\n';
content += '        FailedTests = FailedTests + 1\r\n';
content += '        Debug.Print "  [FAIL] Тест FileExists не пройден"\r\n';
content += '    End If\r\n';
content += '\r\n';
content += '    '' Тест 2: проверка FormatDateSQL\r\n';
content += '    TotalTests = TotalTests + 1\r\n';
content += '    If Test_FormatDateSQL() Then\r\n';
content += '        PassedTests = PassedTests + 1\r\n';
content += '        Debug.Print "  [OK] Тест FormatDateSQL пройден"\r\n';
content += '    Else\r\n';
content += '        FailedTests = FailedTests + 1\r\n';
content += '        Debug.Print "  [FAIL] Тест FormatDateSQL не пройден"\r\n';
content += '    End If\r\n';
content += '\r\n';
content += '    '' Тест 3: проверка FindOrder\r\n';
content += '    TotalTests = TotalTests + 1\r\n';
content += '    If Test_FindOrder() Then\r\n';
content += '        PassedTests = PassedTests + 1\r\n';
content += '        Debug.Print "  [OK] Тест FindOrder пройден"\r\n';
content += '    Else\r\n';
content += '        FailedTests = FailedTests + 1\r\n';
content += '        Debug.Print "  [FAIL] Тест FindOrder не пройден"\r\n';
content += '    End If\r\n';
content += '\r\n';
content += '    '' Итог\r\n';
content += '    Debug.Print "========================================="\r\n';
content += '    Debug.Print "ИТОГО: " & TotalTests & " тестов, " & PassedTests & " пройдено, " & FailedTests & " упало"\r\n';
content += '    Debug.Print "========================================="\r\n';
content += '\r\n';
content += '    MsgBox "Тестирование завершено." & vbCrLf & _\r\n';
content += '           "Всего: " & TotalTests & ", Пройдено: " & PassedTests & ", Упало: " & FailedTests, _\r\n';
content += '           vbInformation, "Результаты тестов"\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Тест: FileExists\r\n";
content += 'Private Function Test_FileExists() As Boolean\r\n';
content += '    On Error Resume Next\r\n';
content += '    '' Проверяем, что функция существует и возвращает Boolean\r\n';
content += '    Dim Result As Boolean\r\n';
content += '    Result = FileExists("C:\\Windows\\notepad.exe")\r\n';
content += '    Test_FileExists = (Err.Number = 0)\r\n';
content += '    On Error GoTo 0\r\n';
content += 'End Function\r\n';
content += '\r\n';
content += "' Тест: FormatDateSQL\r\n";
content += 'Private Function Test_FormatDateSQL() As Boolean\r\n';
content += '    On Error Resume Next\r\n';
content += '    Dim Result As String\r\n';
content += '    Result = FormatDateSQL(DateSerial(2026, 7, 12))\r\n';
content += '    Test_FormatDateSQL = (Result = "2026-07-12")\r\n';
content += '    On Error GoTo 0\r\n';
content += 'End Function\r\n';
content += '\r\n';
content += "' Тест: FindOrder\r\n";
content += 'Private Function Test_FindOrder() As Boolean\r\n';
content += '    On Error Resume Next\r\n';
content += '    Dim Header As OrderHeader\r\n';
content += '    Test_FindOrder = FindOrder("ЗН-001", Header)\r\n';
content += '    On Error GoTo 0\r\n';
content += 'End Function\r\n';
writeFile1251("Mod_MinimalTestRunner.bas", content);

// ============================================================
// 6. Лист1_main.cls
// ============================================================
content = '';
content += 'Attribute VB_Name = "Лист1"\r\n';
content += 'Attribute VB_Exposed = True\r\n';
content += 'Attribute VB_Creatable = False\r\n';
content += 'Attribute VB_PredeclaredId = True\r\n';
content += '\r\n';
content += 'Option Explicit\r\n';
content += '\r\n';
content += "' ============================================================\r\n";
content += "' Модуль: Лист1 (main)\r\n";
content += "' Назначение: обработчики событий главного листа\r\n";
content += "' ============================================================\r\n";
content += '\r\n';
content += "' Событие: изменение ячейки на листе\r\n";
content += 'Private Sub Worksheet_Change(ByVal Target As Range)\r\n';
content += '    '' Делегируем обработку модулю Mod_OrderHeader\r\n';
content += '    Mod_OrderHeader.OnWorksheetChange Target\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Событие: активация листа\r\n";
content += 'Private Sub Worksheet_Activate()\r\n';
content += '    '' Обновляем строку состояния\r\n';
content += '    Application.StatusBar = "Лист1 активен. Режим: ввод заказ-нарядов."\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Событие: деактивация листа\r\n";
content += 'Private Sub Worksheet_Deactivate()\r\n';
content += '    Application.StatusBar = False\r\n';
content += 'End Sub\r\n';
content += '\r\n';
content += "' Событие: двойной щелчок по ячейке\r\n";
content += 'Private Sub Worksheet_BeforeDoubleClick(ByVal Target As Range, Cancel As Boolean)\r\n';
content += '    '' Если двойной щелчок по номеру заказа — открыть детали\r\n';
content += '    If Target.Column = 2 And Target.Row >= 2 Then\r\n';
content += '        If Trim(Target.Value) <> "" Then\r\n';
content += '            MsgBox "Детали заказа: " & Target.Value, vbInformation, "Заказ-наряд"\r\n';
content += '            Cancel = True\r\n';
content += '        End If\r\n';
content += '    End If\r\n';
content += 'End Sub\r\n';
writeFile1251("Лист1_main.cls", content);

WScript.Echo("");
WScript.Echo("All 6 files written successfully in Windows-1251 encoding!");